FROM rabbitmq:3-management

EXPOSE 5672
EXPOSE 15672

#docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq

#  docker run \
#    -itd \
#    -v "scalable-app_mq_log:/var/log/rabbitmq" \
#    -v "scalable-app_mq_data:/var/lib/rabbitmq" \
#    --name "rabbitmq" \
#    --hostname rabbitmq \
#    -p 15672:15672 \
#    -p 5672:5672 \
#    rabbitmq
